blank_issues_enabled: false
contact_links:
  - name: Azure Support
    url: https://azure.microsoft.com/support/create-ticket/
    about: Get help with production incidents, service outages, billing, accounts, subscriptions, quotas, or private resource troubleshooting.
